REM Updating Bginfo...
"%PROGRAMFILES%\Winternals\Bginfo\Bginfo.exe" "%PROGRAMFILES%\Winternals\Bginfo\server_template.bgi" /timer:0 /nolicprompt /silent
RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters